1.Python线程报错Exception in thread Thread-xxx
    报错原因：同一线程运行时间过长
    报错情景：递归调用函数产生线程，在主程序结束后子线程不会自行结束
    改正方法：主程序结束后更新标志，使子线程根据该标志停止递归调用
